#jwt
jwt:
  # 使用Base64对该令牌进行编码 (制定您的密钥) 256 ytkj cnzz
  base64-secret: 4aecf88b17dc6a36b2b67b3a12d91d27ytkjcnzz47fad79add3580342f32661119289a06
  # 令牌过期时间 此处单位/毫秒 24小时
  token-validity-in-seconds: 14400000
  #放行url（静态资源已放行）
  permitMatchers:
    - /JwtTokenController/getToken


server:
  port: 80
  servlet:
    context-path: /jwt
spring:
  application:
    name: redis-demo
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://114.215.104.72:3306/feec_dev?serverTimezone=GMT%2B8&allowMultiQueries=true  # 数据库名称
#    username: zichen
#    password: 62672000
#    dbcp2:
#      min-idle: 5
#      initial-size: 5
#      max-total: 5
#      max-wait-millis: 150

#logback日志配置
logging:
  config: classpath:logback-spring.xml
  debug: false
  level:
    #    这里配置切换根日志root级别   | DEBUG  | INFO | ERROR
    root: DEBUG
    com.yuantiaokj.dao: debug
    #提高日志级别为WARN
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN
    com.netflix: WARN
    org.apache: WARN


## 在被监控服务上添加暴露端点
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream,info,health,scheduledtasks,mappings,metrics,configprops,env,logfile
    logfile:
      external-file: ${logging.path}/paycentre-consumer.log

#微服务info内容详细信息修改
info:
  app.name: test
  company.name: loclhost
  build.artifactId: paycentre-consumer-6021
  build.version: 1.3


#线程池配置参数
task:
  pool:
    corePoolSize: 20 #设置核心线程数
    maxPoolSize: 200  #设置最大线程数
    keepAliveSeconds: 60 #设置线程活跃时间（秒）
    queueCapacity: 500 #设置队列容量

swagger:
  title: jwt-module组件
  description: 接口文档
  version: 1.3
  header: authorization