

####测试

# test Session
POST http://localhost:80/jwt/JwtTokenController/getToken
Accept: */*
Cache-Control: no-cache

####测试

# test Session
POST http://localhost:80/jwt/JwtTokenController/getTokenUser
Accept: */*
Cache-Control: no-cache
token: eyJhbGciOiJIUzI1NiIsInppcCI6IkRFRiJ9.eNqqVkosLclQslJKTMnNzNNJTEspVtJRyirJBAoZGhkD2cWlSUB2cl5VFZCTmViiZGVoZmhqaGliZmKso5RaUQARMDKwNDAxrgUAAAD__w.tbWqDiaNHH8qfHragQHfLrQLJq_gCDbXspruTXtlZ7g

{
}
####测试

# test Session
GET http://localhost:80/jwt/JwtTokenController/validPermission
Accept: */*
Cache-Control: no-cache
//authorization: bearer eyJhbGciOiJIUzI1NiIsInppcCI6IkRFRiJ9.eNqqVkosLclQslJKTMnNzFPSUcoqyQTyTI2BzOLSJCCzKqO0KhPIy0wsUbIyNLU0sLQ0MDE31VFKrSgACxgaGJhYmJvWAgAAAP__.a9IrprBgG_ALaRXdlOPG3so5xyVTmEdAeUzkFACzTEQ
#authorization: bearer eyJhbGciOiJIUzI1NiIsInppcCI6IkRFRiJ9.eNp0Vctu2zAQ_Bedc7BTOKh1c1q0yCFIkKbNoSiEDbm2mUoky0dTp-i_d_UiKUo-2ZwhZ3aXq-XfArw7FuX3wls0tyDhQD-XxcV0Xf3yaE7XboZzrNFhR2g0jbBWKFk1PU-gUTUu7p4SUX6Ke81h6cAsDuB84XhAUSvjbteVhtOd4ZnlUTV4Tydmoom7NuoFmauYkntx8AYc5Uk4U40GeaqE3CvTjKhqPZIqcGE1OHZMIA2CJ8tnsIJVqQuBoLUS0jUoXeVEgyOemI2QQSGtprMtlsloYD_Jxub4QuwVRcpqIC9zZkMMOY2uS5gwy1BiWDEw1Zh6F3YXoUorQ1seTxrLvtQJQJvRuAT4LfA1Wfat1AJHMAchD1-lcGFTikWlFI2GKRpUk-Q-1XAYhXNYaZS7iC3sYLWyeHbLI1X6A91GDGeJDBkskfPIAhWy6brrvr_9aDVBg8cEHcTHDhrhIJwTQTsngnxODA6hf2dKMyZIzZhzWrFX-oa-if2c9MGci50z58ZOmzPBLX5L16cbHp0yPLhk-OCQoUG9HVWfwVAtS65eZa2Aj5OnZCAZ1h_jp9fDPAcMDib9cuedmh8iO-Ye0PraBTAOm2-TOpR7IfnOc-EwRtMn_sWB87ZNqBMk772XPG-4_KqGw1FyoeAGuWdnrtCAsC2Ff9oXoBwn07Ck5-CJ1M1CXk8gJi8H1Z8mhXTTx2qB7aWLHxfFixNFWWzetXPRP9Pft6N_E-0gBFeU6812td2u3l9tu3A6YL1abS6vtv_-AwAA__8.jcUORinfyxS3bS6H_2tI7oYLuOffYZhTDaAm_Sbfqqs
authorization: bearer eyJhbGciOiJIUzI1NiIsInppcCI6IkRFRiJ9.eNqqVkosLclQslJKTMnNzNNJTEspVtJRyirJBAoZGhkZAznFpUkg-aTkZCAnM7FEycrQ1NLQzMzU1MBMRym1ogAqYG5paWBWCwAAAP__.XNaK2-Vglemt8Qr9ZGFQJ-9hNH7tD9LG2mJKYmOY60w
        ####



####测试

# test Session
GET http://localhost:80/jwt/JwtTokenController/validPermission
Accept: */*
Cache-Control: no-cache
//authorization: bearer eyJhbGciOiJIUzI1NiIsInppcCI6IkRFRiJ9.eNqqVkosLclQslJKTMnNzFPSUcoqyQTyTI2BzOLSJCCzKqO0KhPIy0wsUbIyNLU0sLQ0MDE31VFKrSgACxgaGJhYmJvWAgAAAP__.a9IrprBgG_ALaRXdlOPG3so5xyVTmEdAeUzkFACzTEQ
#authorization: bearer eyJhbGciOiJIUzI1NiIsInppcCI6IkRFRiJ9.eNp0Vctu2zAQ_Bedc7BTOKh1c1q0yCFIkKbNoSiEDbm2mUoky0dTp-i_d_UiKUo-2ZwhZ3aXq-XfArw7FuX3wls0tyDhQD-XxcV0Xf3yaE7XboZzrNFhR2g0jbBWKFk1PU-gUTUu7p4SUX6Ke81h6cAsDuB84XhAUSvjbteVhtOd4ZnlUTV4Tydmoom7NuoFmauYkntx8AYc5Uk4U40GeaqE3CvTjKhqPZIqcGE1OHZMIA2CJ8tnsIJVqQuBoLUS0jUoXeVEgyOemI2QQSGtprMtlsloYD_Jxub4QuwVRcpqIC9zZkMMOY2uS5gwy1BiWDEw1Zh6F3YXoUorQ1seTxrLvtQJQJvRuAT4LfA1Wfat1AJHMAchD1-lcGFTikWlFI2GKRpUk-Q-1XAYhXNYaZS7iC3sYLWyeHbLI1X6A91GDGeJDBkskfPIAhWy6brrvr_9aDVBg8cEHcTHDhrhIJwTQTsngnxODA6hf2dKMyZIzZhzWrFX-oa-if2c9MGci50z58ZOmzPBLX5L16cbHp0yPLhk-OCQoUG9HVWfwVAtS65eZa2Aj5OnZCAZ1h_jp9fDPAcMDib9cuedmh8iO-Ye0PraBTAOm2-TOpR7IfnOc-EwRtMn_sWB87ZNqBMk772XPG-4_KqGw1FyoeAGuWdnrtCAsC2Ff9oXoBwn07Ck5-CJ1M1CXk8gJi8H1Z8mhXTTx2qB7aWLHxfFixNFWWzetXPRP9Pft6N_E-0gBFeU6812td2u3l9tu3A6YL1abS6vtv_-AwAA__8.jcUORinfyxS3bS6H_2tI7oYLuOffYZhTDaAm_Sbfqqs
#authorization: bearer eyJhbGciOiJIUzI1NiIsInppcCI6IkRFRiJ9.eNqqVkosLclQsopWSkzJzcxTitVRyirJVLJSMlTSUSouTQKyqjJKqzKBvMzEEiUrQ1NLQyNTSwsjYx2l1IoCqIC5iZGRcS0AAAD__w.FLyhlJEJDwiTVKlONpnxktokn4EAFj8EvbYtNoTRMcg
authorization: bearer eyJhbGciOiJIUzI1NiIsInppcCI6IkRFRiJ9.eNqqVkosLclQslJKTMnNzNNJTEspVtJRyirJBAoZGhkZAznFpUkg-aTkZCAnM7FEycrQzMDczMTc3MRYRym1ogAqYGZkaGJcCwAAAP__._XE-2ClpsbG9dFeq8LXD83QUUNZLBNGdfQJApDG46d0

###
        ####


